### ISSUE TITLE
Does not render with React Native Web using Expo. 

### ISSUE THREAD

**Issue by Lurtroxx** [connectedcars/react-native-slide-charts#37] opened 2021-09-09 15:42 UTC
I cannot get the component to render using the web. It also does not render on the snack for the example.

**Comment by Lurtroxx** [comment] 2021-09-09 15:43
Wrong repo. Sorry.

**Comment by Kjagd** [comment] 2021-09-10 09:31
Hi, unfortunately something is broken with Expo. It doesn't seem that trivial to fix unfortunatly. Closing since it's a duplicate of https://github.com/connectedcars/react-native-slide-charts/issues/11

**Closed by Kjagd** 2021-09-10 09:31 UTC
